/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import DAO.classes.*;

import de.javasoft.plaf.synthetica.SyntheticaBlueLightLookAndFeel;
import entities.Admin;
import entities.Client;
import entities.Gerant;
import exception.AdminException;

import java.text.ParseException;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author anwer
 */
public class Inscription extends javax.swing.JFrame {

    /**
     * Creates new form Insription
     */
    public Inscription() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TfPrenom = new javax.swing.JTextField();
        TfLogin = new javax.swing.JTextField();
        TfAdr = new javax.swing.JTextField();
        TfEmail = new javax.swing.JTextField();
        TfTel = new javax.swing.JTextField();
        TfNom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmdValiderInscri = new javax.swing.JButton();
        motDePasse2 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        TfMP1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 1200));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setText("Nom");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel2.setText("Prénom");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel4.setText("Téléphone");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setText("Adresse Postal");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel6.setText("E-mail");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel7.setText(" Retaper mot de passe");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel9.setText("Login");

        TfPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPrenomActionPerformed(evt);
            }
        });

        TfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfLoginActionPerformed(evt);
            }
        });

        TfAdr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfAdrActionPerformed(evt);
            }
        });

        TfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEmailActionPerformed(evt);
            }
        });

        TfTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfTelActionPerformed(evt);
            }
        });

        TfNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfNomActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel8.setText("Inscrivez Vous !");

        cmdValiderInscri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdValiderInscri.setText("Valider");
        cmdValiderInscri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdValiderInscriMouseClicked(evt);
            }
        });
        cmdValiderInscri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdValiderInscriActionPerformed(evt);
            }
        });

        motDePasse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motDePasse2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel11.setText("Mot de passe");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfMP1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(motDePasse2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TfAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(TfNom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(TfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(TfTel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmdValiderInscri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(TfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TfAdr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TfMP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(motDePasse2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cmdValiderInscri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TfNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfNomActionPerformed

    private void TfTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfTelActionPerformed

    private void TfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEmailActionPerformed

    private void TfAdrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfAdrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfAdrActionPerformed

    private void TfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfLoginActionPerformed

    private void TfPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPrenomActionPerformed

    private void cmdValiderInscriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdValiderInscriMouseClicked
              // TODO add your handling code here:
               
    }//GEN-LAST:event_cmdValiderInscriMouseClicked

    private void cmdValiderInscriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdValiderInscriActionPerformed

       
            
               String EMAIL ="^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
              String nom="^[a-zA-Z]+$";
              String prenom="^[a-zA-Z]+$";
              
           Client client= new Client();
          client.setPrenom(TfPrenom.getText().toString());
        client.setNom(TfNom.getText().toString());
        client.setEmail(TfEmail.getText().toString());
          Pattern pattern = Pattern.compile(EMAIL);
         Matcher matcher = pattern.matcher(client.getEmail());
          Pattern pattern1 = Pattern.compile(nom);
         Matcher matcher1 = pattern1.matcher(client.getNom());
           Pattern pattern2 = Pattern.compile(prenom);
         Matcher matcher2 = pattern2.matcher(client.getPrenom());
         
    client.setTelephone(TfTel.getText());
        client.setPass(TfMP1.getText().toString());
        client.setAdresse(TfAdr.getText().toString());
        client.setTelephone(TfTel.getText());
     
         client.setLogin(TfLogin.getText().toString());
        
        String motdepasse2 = motDePasse2.getText().toString();
        
        
       ClientDAO admindao = new ClientDAO ();
       
        

        try {

            if (client.getNom().equals("")) {
                throw new AdminException("svp ! tapez votre nom");
            }
              if (!matcher1.matches()) {
                       throw new AdminException("tapez  un    nom  valide svp");
                   }
            
            if (client.getNom().length() > 30) {
                throw new AdminException("nom est trop long");
            }
            if (client.getPrenom().equals("")) {

                throw new AdminException("Tapez votre Prenom svp ");
            }
              if (!matcher2.matches()) {
                       throw new AdminException("tapez un prenom valide svp");
                   }
            if (client.getPrenom().length() > 30) {
                throw new AdminException("prenom est trop long");
            }
            if (client.getTelephone().equals("")) {

                throw new AdminException("Tapez votre Telephone svp ");
            }
            if (client.getTelephone().length() > 12) {
                throw new AdminException("Telephone est trop long");
            }
            if (client.getEmail().equals("")) {

                throw new AdminException("Tapez votre Emailsvp ");
            }
             if (!matcher.matches()) {
                       throw new AdminException("tapez  une adresse  email valide svp");
                   }
            if (client.getEmail().length() > 30) {
                throw new AdminException("Email est trop long");
            }
             if (client.getAdresse().equals("")) {

                throw new AdminException("Tapez votre Adresse svp ");
            }
            if (client.getAdresse().length() > 30) {
                throw new AdminException("Adresse est trop long");
            }
            
             if (client.getLogin().equals("")) {
                throw new AdminException("tapez votre Login de passe svp ");
            }
            if (client.getLogin().length() > 30) {
                throw new AdminException("login est trop long");
            }
              if (client.getPass().equals("")) {
                throw new AdminException("tapez votre mot de passe svp ");
            }
            if (client.getPass().length() > 30) {
                throw new AdminException("mot de passe  est trop long");
            }
           
            if (motdepasse2.equals("")) {
                throw new AdminException("retapez votre  mot de passe svp ");
            }
            if (!motdepasse2.equals(client.getPass())) {
                throw new AdminException(" les deux mot de passe ne sont pas identique");
            }
            
            admindao.ajoutClient(client);
            JOptionPane.showMessageDialog(null, "client ajouter", "OK", JOptionPane.OK_CANCEL_OPTION);
            cmdValiderInscri.setEnabled(true);//ouis chager false
         
        } catch (AdminException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
                   
              
//         if (combox1.getSelectedItem().toString().equals("gerant")) { 
//              String EMAIL ="^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
//              String nom="^[a-zA-Z]+$";
//              String prenom="^[a-zA-Z]+$";
//        Gerant gerant= new Gerant();
//          gerant.setPrenom(TfPrenom.getText().toString());
//        gerant.setNom(TfNom.getText().toString());
//       gerant.setEmail(TfEmail.getText().toString());
//     Pattern pattern = Pattern.compile(EMAIL);
//         Matcher matcher = pattern.matcher( gerant.getEmail());
//         Pattern pattern1 = Pattern.compile(nom);
//         Matcher matcher1 = pattern1.matcher(gerant.getNom());
//           Pattern pattern2 = Pattern.compile(prenom);
//         Matcher matcher2 = pattern2.matcher(gerant.getPrenom());
//         
//    gerant.setTelephone(TfTel.getText());
//        gerant.setPass(TfMP1.getText().toString());
//        gerant.setAdresse(TfAdr.getText().toString());
//        gerant.setTelephone(TfTel.getText());
//     
//         gerant.setLogin(TfLogin.getText().toString());
//        
//        String motdepasse2 = motDePasse2.getText().toString();
//        
//        
//       GerantDAO gerantDAO= new GerantDAO  ();
//       
//        
//
//        try {
//
//            if (gerant.getNom().equals("")) {
//                throw new AdminException("svp ! tapez votre nom");
//            }
//            if (!matcher1.matches()) {
//                       throw new AdminException("tapez  un    nom  valide svp");
//                   }
//            
//            if (gerant.getNom().length() > 30) {
//                throw new AdminException("nom est trop long");
//            }
//            if (gerant.getPrenom().equals("")) {
//
//                throw new AdminException("Tapez votre Prenom svp ");
//            }
//            if (!matcher2.matches()) {
//                       throw new AdminException("tapez un prenom valide svp");
//                   }
//            if (gerant.getPrenom().length() > 30) {
//                throw new AdminException("prenom est trop long");
//            }
//            if (gerant.getTelephone().equals("")) {
//
//                throw new AdminException("Tapez votre Telephone svp ");
//            }
//            if (gerant.getTelephone().length() > 30) {
//                throw new AdminException("Telephone est trop long");
//            }
//            if (gerant.getEmail().equals("")) {
//
//                throw new AdminException("Tapez votre Emailsvp ");
//            }
//             if (!matcher.matches()) {
//                       throw new AdminException("tapez  une adresse  email valide svp");
//                   }
//            if (gerant.getEmail().length() > 30) {
//                throw new AdminException("Email est trop long");
//            }
//             if (gerant.getAdresse().equals("")) {
//
//                throw new AdminException("Tapez votre Adresse svp ");
//            }
//            if (gerant.getAdresse().length() > 30) {
//                throw new AdminException("Adresse est trop long");
//            }
//            
//             if (gerant.getLogin().equals("")) {
//                throw new AdminException("tapez votre Login de passe svp ");
//            }
//            if (gerant.getLogin().length() > 30) {
//                throw new AdminException("login est trop long");
//            }
//              if (gerant.getPass().equals("")) {
//                throw new AdminException("tapez votre mot de passe svp ");
//            }
//            if (gerant.getPass().length() > 30) {
//                throw new AdminException("mot de passe  est trop long");
//            }
//           
//            if (motdepasse2.equals("")) {
//                throw new AdminException("retapez votre  mot de passe svp ");
//            }
//            if (!motdepasse2.equals(gerant.getPass())) {
//                throw new AdminException(" les deux mot de passe ne sont pas identique");
//            }
//            
//            gerantDAO.ajoutGerant(gerant);
//            JOptionPane.showMessageDialog(null, "gerant ajouter", "OK", JOptionPane.OK_CANCEL_OPTION);
//            cmdValiderInscri.setEnabled(true);//ouis chager false
//         
//        } catch (AdminException e) {
//            JOptionPane.showMessageDialog(null, e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
//        }
//        }           

    }//GEN-LAST:event_cmdValiderInscriActionPerformed

    private void motDePasse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motDePasse2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motDePasse2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new SyntheticaBlueLightLookAndFeel());
               
                new Inscription().setVisible(true);
                 } catch (ParseException ex) {
                    Logger.getLogger(Inscription.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Inscription.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfAdr;
    private javax.swing.JTextField TfEmail;
    private javax.swing.JTextField TfLogin;
    private javax.swing.JPasswordField TfMP1;
    private javax.swing.JTextField TfNom;
    private javax.swing.JTextField TfPrenom;
    private javax.swing.JTextField TfTel;
    private javax.swing.JButton cmdValiderInscri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField motDePasse2;
    // End of variables declaration//GEN-END:variables
}
